### ISSUE TITLE
Humann2_go_abundances identifier issue

### ISSUE THREAD

**Issue by jraysajulga** [ASaiM/group_humann2_uniref_abundances_to_GO#10]
@bebatut 

If I use this input file,
```
# Gene Family	humann2_Abundance-RPKs
UNMAPPED	6733023.0000000000
UniRef50_P62593: Beta-lactamase TEM	1047701.6397731160
UniRef50_P62593: Beta-lactamase TEM|g__Clostridium.s__Clostridium_thermocellum	1047701.6397731160
UniRef50_G8LZ61	302275.8103299162
UniRef50_G8LZ61|g__Clostridium.s__Clostridium_thermocellum	302275.8103299162
UniRef50_B3EQQ7: 50S ribosomal protein L34	273923.7863211943
UniRef50_B3EQQ7: 50S ribosomal protein L34|g__Clostridium.s__Clostridium_thermocellum	273923.7863211943
UniRef50_E6UMP2	267546.3811701911
UniRef50_E6UMP2|g__Clostridium.s__Clostridium_thermocellum	267546.3811701911=
```

I run into this error:
```
Format slim GO abundance
========================
Traceback (most recent call last):
  File "./src/format_humann2_output.py", line 93, in <module>
    format_humann2_output(args, go_annotations)
  File "./src/format_humann2_output.py", line 70, in format_humann2_output
    namespace = go_annotations[go_id]["namespace"]
KeyError: 'UNGROUPED|g__Clostridium.s__Clostridium_thermocellum'
```

The `humann2_go_abundances.txt` intermediate file looks like this:
```
# Gene Family	humann2_Abundance-RPKs
UNMAPPED	6733023.0
UNGROUPED	569822.192
UNGROUPED|g__Clostridium.s__Clostridium_thermocellum	569822.192
GO:0003735	273923.786
GO:0003735|g__Clostridium.s__Clostridium_thermocellum	273923.786
GO:0005622	273923.786
GO:0005622|g__Clostridium.s__Clostridium_thermocellum	273923.786
GO:0005840	273923.786
GO:0005840|g__Clostridium.s__Clostridium_thermocellum	273923.786
GO:0006412	273923.786
GO:0006412|g__Clostridium.s__Clostridium_thermocellum	273923.786
GO:0016812	1047701.64
GO:0016812|g__Clostridium.s__Clostridium_thermocellum	1047701.64
GO:0046677	1047701.64
GO:0046677|g__Clostridium.s__Clostridium_thermocellum	1047701.64
```

How should we handle this? I think we need to separate the GO id from the taxonomy identifier but can we also keep the tax id in the output?

**Comment by bebatut** [comment]
Hi @jraysajulga,

Did you identify the issue? Is #10 fixing it?

Bérénice

**Comment by jraysajulga** [comment]
Hi @bebatut,

I modified the code to add a Misc. column that contains this extra identifier information. Here's an example:

```
GO id	GO name	Abundance	Misc.
GO:0006412	translation	273923.786	
GO:0006412	translation	273923.786	g__Clostridium.s__Clostridium_thermocellum
GO:0042221	response to chemical	1047701.64	
GO:0042221	response to chemical	1047701.64	g__Clostridium.s__Clostridium_thermocellum
```

**Comment by jraysajulga** [comment]
With another dataset, you can see the taxa distribution associated with a function:

```
GO:0003676	nucleic acid binding	215977.665	
GO:0003676	nucleic acid binding	32414.276	g__Clostridium.s__Clostridium_thermocellum
GO:0003676	nucleic acid binding	182515.851	g__Coprothermobacter.s__Coprothermobacter_proteolyticus
GO:0003676	nucleic acid binding	161.794	g__Escherichia.s__Escherichia_coli
GO:0003676	nucleic acid binding	885.746	g__Methanothermobacter.s__Methanothermobacter_thermautotrophicus
```
